apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "v1"
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
    verbs:
      - list
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.name }}
